### ISSUE TITLE
No AUX output from the virtual-analog engine

### ISSUE THREAD

**Issue by crp500** [sourcebox/mi-plaits-dsp-rs#2] opened 2023-04-23 10:37 UTC
I get AUX output from all engines except the virtual-analog engine.

The manual says:
AUX: sum of two hardsync’ed waveforms, the shape of which is controlled by MORPH and detuning by HARMONICS.

I am using the engine through voice.rs
No errors or crashes or anything in the audio other than silence. The main virtual-analog output is fine.

**Comment by sourcebox** [comment] 2023-04-23 13:15
I added a test for the voice module which generates output under `out/voice`. I can confirm that the aux output is silent when `harmonics` and `timbre` are both set to `0.5`. By changing `harmonics` to `0.6` and `timbre` to `0.4`, some output will be generated.

@crp500 can you please check that behaviour and compare it to the hardware module? I'm quite sure there is some error in the code, but I'd like to have it checked against the original before further investigation.

**Comment by sourcebox** [comment] 2023-04-23 17:18
After some further investigation, I found that having a value of exactly `0.5` for `harmonics` causes the aux output to be silent. Changing the value slightly above or below `0.5` will give some output signal. So I'm not sure, if there is really an error in the code or if it's the desired behaviour.

I guess that with the hardware module it's nearly impossible to match that value exactly because the pot setting is always quantized to a step because of limited resolution.

**Comment by crp500** [comment] 2023-04-24 00:01
Harmonics seems to be the problem for me.
If Harmonics is set to 0.5 on startup then there is no sound even when timbre/morph are set to values other than 0.5 on startup. Also, if i move timbre/morph after startup (while leaving harmonics at 0.5) there is still no sound.

If Harmonics is any other value than 0.5 at startup then i get sound.

If Harmonics is 0.5 at strartup I get sound as soon as I move Harmonics off 0.5 and then after that i can move harmonics back to 0.5 and the sound continues to output.

I also noticed the same behaviour for the modulations_harmonics parameter.
patch_harmonics = 0.5 + modulations_harmonics = 0 causes no sound
modulations_harmonics > 0 or < 0 causes sound

I could not repeat this behaviour on a genuine MU plaits hardware. 
I could not get it to go silent no matter how close i tried to position harmonics to "12 oclock" which i presume is the equivalent of 0.5

**Comment by sourcebox** [comment] 2023-04-24 08:37
Please check the latest commit. I put an offset on the start phase of the aux oscillator, so the waveforms shouldn't cancel out each other anymore.

**Comment by crp500** [comment] 2023-04-24 21:12
That seems to have fixed things.

**Comment by sourcebox** [comment] 2023-04-25 08:13
Closed via ceff2993d61c9c382c9a2e57ed7924fe5e9d180a

**Closed by sourcebox** 2023-04-25 08:13 UTC
